const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const dist = path.join(__dirname, 'dist');
const assets = JSON.parse(fs.readFileSync(path.join(dist, 'assets', 'characters.json'), 'utf8'));
const mimes = { '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.webp': 'image/webp', '.gif': 'image/gif' };
assert.equal(assets.length, require('./dist/engine.js').TYPES.length);
const embedded = assets.map(({ name, file, source }) => ({ name, file, source, data: 'data:' + mimes[path.extname(file)] + ';base64,' + fs.readFileSync(path.join(dist, 'assets', file)).toString('base64') }));
let html = fs.readFileSync(path.join(dist, 'index.html'), 'utf8');
html = html.replace(/<link rel="stylesheet" href="style.css">/, '<style>' + fs.readFileSync(path.join(dist, 'style.css'), 'utf8') + '</style>');
html = html.replace(/<script src="engine.js" defer><\/script>/, '<script>window.NAILONG_ASSETS=' + JSON.stringify(embedded).replace(/</g, '\\u003c') + ';\n' + fs.readFileSync(path.join(dist, 'engine.js'), 'utf8') + '</script>');
html = html.replace(/<script src="app.js" defer><\/script>/, '');
html = html.replace('</body>', '<script>' + fs.readFileSync(path.join(dist, 'app.js'), 'utf8') + '</script>\n</body>');
html = html.replace(/href="assets\/[^\"]+" type="image\/[^\"]+"/, 'href="' + embedded[0].data + '" type="' + mimes[path.extname(assets[0].file)] + '"');
html = html.replace(/src="assets\/[^\"]+" width="44"/, 'src="' + embedded[0].data + '" width="44"');
assert.ok(!/<script src=|<link rel="stylesheet"|src="assets\//.test(html));
const output = path.resolve(__dirname, '..', 'output', 'catch-nailong', '抓奶龙.html');
fs.mkdirSync(path.dirname(output), { recursive: true }); fs.writeFileSync(output, html);
console.log(JSON.stringify({ output, bytes: Buffer.byteLength(html), characters: embedded.map(x => x.name) }));
