const test = require('node:test');
const assert = require('node:assert/strict');
const { Game, LEVELS, canPick, project, hit, TYPES } = require('../dist/engine.js');
function clearInReverse(game) { let safety = 300; while (game.status === 'playing' && game.board.length && safety--) { const result = game.pick(game.board.at(-1).id); assert.equal(result.ok, true); } assert.equal(game.status, 'won'); assert.equal(game.tray.length, 0); assert.equal(game.removed, game.total); }
function setState(game, types, boardTypes) { game.tray = types.map((type, id) => ({ id: 100 + id, type })); game.board = boardTypes.map((type, id) => ({ id, type, x: 50 + id * 70, y: 100, radius: 34, angle: 0 })); game.total = types.length + boardTypes.length; game.status = 'playing'; }
test('All three levels have a legal winning route over 50 different layouts', () => { for (let level = 0; level < LEVELS.length; level++) for (let seed = 1; seed <= 50; seed++) { const game = new Game(level, seed); assert.equal(new Set(game.board.slice(-3).map(x => x.type)).size, 3); game.start(); clearInReverse(game); } });
test('Seventh slot that completes a triple is cleared before overflow', () => { const game = new Game(); setState(game, [0, 0, 1, 2, 3, 4], [0]); const result = game.pick(0); assert.equal(result.matched, true); assert.equal(game.tray.length, 4); assert.equal(game.status, 'playing'); });
test('Seventh unmatched item fails; undo restores playable state', () => { const game = new Game(); setState(game, [0, 1, 2, 3, 4, 5], [6]); game.pick(0); assert.equal(game.status, 'full'); assert.equal(game.undo(), true); assert.equal(game.status, 'playing'); assert.equal(game.tray.length, 6); assert.equal(game.board.length, 1); assert.equal(game.tools.undo, 2); });
test('Undo restores the complete pre-match state without restoring time', () => { const game = new Game(); setState(game, [0, 0], [0, 1, 1, 1]); const before = game.board.length; game.pick(0); assert.equal(game.tray.length, 0); game.tick(4); assert.equal(game.undo(), true); assert.equal(game.board.length, before); assert.deepEqual(game.tray.map(x => x.type), [0, 0]); assert.equal(game.removed, 0); assert.equal(game.remaining, 116); });
test('Paused, ready, won, and timeout states cannot consume time or pick items', () => { const game = new Game(); const id = game.board.at(-1).id; game.tick(10); assert.equal(game.remaining, 120); assert.equal(game.pick(id).ok, false); game.start(); game.tick(5); game.pause(); game.tick(500); assert.equal(game.remaining, 115); assert.equal(game.pick(id).ok, false); game.start(); game.tick(115); assert.equal(game.status, 'timeout'); assert.equal(game.pick(id).ok, false); assert.equal(game.undo(), false); });
test('Covered item cannot be grabbed and repeated id cannot duplicate a capture', () => { const game = new Game(); setState(game, [], [0, 0]); game.board[1].x = game.board[0].x; assert.equal(canPick(game.board, 0), false); assert.equal(game.pick(0).ok, false); assert.equal(game.pick(1).ok, true); assert.equal(game.pick(1).ok, false); assert.equal(game.board.length, 1); });
test('Shaking retains the collection and offers a winning route with pairs and singles', () => { for (let n = 0; n < 22; n++) { const game = new Game(1, 41); game.start(); for (let i = 0; i < n; i++) game.pick(game.board.at(-1).id); const tray = game.tray.map(x => x.id); assert.equal(game.shake(), true); assert.deepEqual(game.tray.map(x => x.id), tray); assert.equal(game.tools.shake, 2); clearInReverse(game); } const mixed = new Game(1); setState(mixed, [0, 0, 1, 2], [0, 1, 1, 2, 2, 3, 3, 3]); assert.equal(mixed.shake(), true); clearInReverse(mixed); });
test('Impossible six-single tray asks for undo without wasting shake or hint', () => { const game = new Game(); setState(game, [0, 1, 2, 3, 4, 5], [0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5]); assert.equal(game.shake(), false); assert.equal(game.tools.shake, 3); assert.equal(game.hint(), null); assert.equal(game.tools.hint, 3); });
test('Hint selects an exposed existing pair before a new type', () => { const game = new Game(); setState(game, [0, 0], [0, 1, 2]); assert.equal(game.hint().type, 0); assert.equal(game.tools.hint, 2); });
test('All tools stop after their three uses and invalid level is rejected', () => { const game = new Game(1); game.start(); for (let i = 0; i < 3; i++) assert.equal(game.shake(), true); assert.equal(game.shake(), false); for (let i = 0; i < 3; i++) assert.ok(game.hint()); assert.equal(game.hint(), null); assert.throws(() => new Game(99), /关卡不存在/); });
test('Z height determines coverage even when the array order is reversed', () => { const game = new Game(); setState(game, [], [0, 1]); game.board.forEach(item => { item.x = 200; item.y = 200; item.angle = .5; }); game.board[0].z = 8; game.board[1].z = 2; assert.equal(canPick(game.board, 0), true); assert.equal(canPick(game.board, 1), false); const top = project(game.board[0]); assert.equal(hit(game.board[0], top.x, top.y), true); assert.equal(game.pick(1).ok, false); assert.equal(game.pick(0).ok, true); assert.equal(canPick(game.board, 0), true); });
test('Thirty-two characters and deep free-form piles replace the small grid layout', () => { const game = new Game(2, 11); assert.equal(TYPES.length, 32); assert.equal(game.total, 288); assert.equal(new Set(game.board.map(x => x.type)).size, 32); assert.ok(Math.max(...game.board.map(x => x.z)) > 30); assert.ok(new Set(game.board.map(x => x.x)).size > 250); const oldHeights = new Map(game.board.map(x => [x.id, x.z])); game.start(); assert.equal(game.shake(), true); assert.ok(game.board.filter(x => oldHeights.get(x.id) !== x.z).length > 250); clearInReverse(game); });
test('Hint cannot add a sixth singleton when existing matches are buried', () => { const game = new Game(); setState(game, [0, 1, 2, 3, 4], [0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 5]); game.board.forEach((item, i) => { item.x = 100; item.y = 100; item.z = i * .14; }); assert.equal(game.hint(), null); assert.equal(game.tools.hint, 3); });
test('Every exposed card center hits that same card under the pointer rule', () => { const game = new Game(0, 2); const front = [...game.board].sort((a, b) => b.z - a.z); for (const [index, item] of game.board.entries()) { if (!canPick(game.board, index)) continue; const center = project(item); assert.equal(front.find(x => hit(x, center.x, center.y)).id, item.id); } });
